const PLAYERS = [
  {'name': 'Rouge',  'color': '#FF0000'},
  {'name': "Vert",   'color': '#00FF00'},
  {'name': "Bleu",   'color': '#0000FF'},
  {'name': "Blanc",  'color': '#FFFFFF'},
  {'name': "Orange", 'color': '#FF9632'},
  {'name': "Jaune",  'color': '#FFFF00'},
  {'name': "Violet", 'color': '#6400C8'},
  {'name': "Noir",   'color': '#141414'},
]


const TEAMS = {
  4: {'Shadow': 2, 'Neutral': 0, 'Hunter': 2},
  5: {'Shadow': 2, 'Neutral': 1, 'Hunter': 2},
  6: {'Shadow': 2, 'Neutral': 2, 'Hunter': 2},
  7: {'Shadow': 3, 'Neutral': 1, 'Hunter': 3},
  8: {'Shadow': 3, 'Neutral': 2, 'Hunter': 3}
};


const CHARACTERS = {
  'Shadow': [
    {'name': 'Métamorphe',
    'hp': 11,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Pouvoir permanent : Imitation",
    'ability_desc': "Vous pouvez mentir (sans\navoir à révéler votre identité)\nlorsqu'on vous donne\nune carte Vision."},
    {'name': 'Momie',
    'hp': 11,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Capacité spéciale :\nRayon d'Outremonde",
    'ability_desc': "Au début de votre tour,\nvous pouvez infliger 3 Blessures\nà un joueur présent dans le Lieu\nPorte de l'Outremonde."},
    {'name': 'Vampire',
    'hp': 13,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Capacité spéciale : Morsure",
    'ability_desc': "Si vous attaquez un joueur\net lui infligez des Blessures,\nsoignez immédiatement\n2 de vos Blessures."},
    {'name': 'Valkyrie',
    'hp': 13,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Capacité spéciale : Chant de guerre",
    'ability_desc': "Quand vous attaquez,\nlancez seulement le dé à 4 faces\npour déterminer les dégats."},
    {'name': 'Loup-Garou',
    'hp': 14,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Capacité spéciale : Contre-attaque",
    'ability_desc': "Après avoir subi l'attaque\nd'un joueur, vous pouvez\ncontre-attaquer immédiatement."},
    {'name': 'Liche',
    'hp': 14,
    'victory': "Tous les personnages Hunter\nsont morts ou 3 personnages\nNeutres sont morts.",
    'ability': "Capacité spéciale : Nécromancie",
    'ability_desc': "Vous pouvez rejouer autant de fois\nqu'il y a de personnages morts.\nUtilisation unique."}
  ],
  'Neutral': [
    {'name': 'Allie',
    'hp': 8,
    'victory': "Etre encore en vie lorsque\nla partie se termine.",
    'ability': "Capacité spéciale : Amour maternel",
    'ability_desc': "Soignez toutes vos blessures.\nUtilisation unique."},
    {'name': 'Agnes',
    'hp': 8,
    'victory': "Le joueur à votre droite gagne.",
    'ability': "Capacité spéciale : Caprice",
    'ability_desc': "Au début de votre tour, changez\nvotre condition de victoire par :\n\"Le joueur à votre gauche gagne\""},
    {'name': 'Daniel',
    'hp': 13,
    'victory': "Etre le premier à mourir\nOU être en vie quand tous\nles personnages Shadow\nsont morts.",
    'ability': "Particularité : Désespoir",
    'ability_desc': "Dès qu'un personnage meurt,\nvous devez révéler\nvotre identité."},
    {'name': 'David',
    'hp': 13,
    'victory': "Avoir au minimum 3 de ces cartes :\nCrucifix en argent, Amulette,\nLance de Longinus, Toge sainte.",
    'ability': "Capacité spéclass :\nPilleur de tombes",
    'ability_desc': "Récupérez dans la défausse la\ncarte équipement de votre choix.\nUtilisation unique."},
    {'name': 'Charles',
    'hp': 11,
    'victory': "Tuer un personnage par\nune attaque alors qu'il y a\ndéjà eu 3 morts ou plus.",
    'ability': "Capacité spéciale : Festin sanglant",
    'ability_desc': "Après votre attaque, vous pouvez\nvous infliger 2 Blessures afin\nd'attaquer de nouveau\nle même joueur."},
    {'name': 'Catherine',
    'hp': 11,
    'victory': "Être la première à mourir\nOU être l'un des deux\nseuls personnages en vie.",
    'ability': "Capacité spéciale : Stigmates",
    'ability_desc': "Guerissez de 1 Blessure\nau début de votre tour."},
    {'name': 'Bryan',
    'hp': 10,
    'victory': "Tuer un personnage de\n13 Points de Vie ou plus,\nOU être dans le Sanctuaire ancien\nà la fin du jeu.",
    'ability': "Particularité : Oh my god !",
    'ability_desc': "Si vous tuez un personnage de\n12 Points de Vie ou moins,\nvous devez révéler votre identité."},
    {'name': 'Bob',
    'hp': 10,
    'victory': "Posséder 5 cartes équipements\nou plus.",
    'ability': "Capacité spéciale : Braquage",
    'ability_desc': "Si vous tuez un personnage,\nvous pouvez récupérer\ntoutes ses cartes équipements."}
  ],
  'Hunter': [
    {'name': 'Emi',
    'hp': 10,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale : Téléportation",
    'ability_desc': "Pour vous déplacer, vous pouvez\nlancer normalement les dés,\nou vous déplacer sur\nla carte lieu adjacente."},
    {'name': 'Ellen',
    'hp': 10,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale : Exorcisme",
    'ability_desc': "Au début de votre tour,\nvous pouvez désigner un joueur.\nIl perd sa capacité spéciale\njusqu'à la fin de la partie.\nUtilisation unique."},
    {'name': 'Georges',
    'hp': 14,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale : Démolition",
    'ability_desc': "Au début de votre tour, choisissez\nun joueur et infligez lui autant\nde blessures que le résultat\nd'un dé à 4 faces.\nUtilisation unique."},
    {'name': 'Gregor',
    'hp': 14,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale :\nBouclier fantôme",
    'ability_desc': "Ce pouvoir peut s'activer à la fin\nde votre tour. Vous ne subissez\naucune Blessure jusqu'au début\nde votre prochain tour.\nUtilisation unique."},
    {'name': 'Franklin',
    'hp': 12,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale : Poudre",
    'ability_desc': "Au début de votre tour, choisissez\nun joueur et infligez lui autant\nde blessures que le résultat\nd'un dé à 6 faces.\nUtilisation unique."},
    {'name': 'Fu-Ka',
    'hp': 12,
    'victory': "Tous les personnages Shadow\nsont morts.",
    'ability': "Capacité spéciale :\nSoins particuliers",
    'ability_desc': "Au début de votre tour,\nplacez le marqueur\nde Blessures d'un joueur sur 7.\nUtilisation unique."}
  ]
};


const AREAS = [
  {'values': [2, 3], 'name': "Antre de l'ermite",     'text': "Vous pouvez piocher\nune carte Vision"},
  {'values': [4, 5], 'name': "Porte de l'Outremonde", 'text': "Vous pouvez piocher\nune carte dans la pile\nde votre choix"},
  {'values': [6],    'name': "Monastère",             'text': "Vous pouvez piocher\nune carte Lumière"},
  {'values': [8],    'name': "Cimetière",             'text': "Vous pouvez piocher\nune carte Ténèbres"},
  {'values': [9],    'name': "Forêt hantée",          'text': "Le joueur de votre choix\npeut subir 2 blessures\nOU soigner 1 blessure"},
  {'values': [10],   'name':  "Sanctuaire ancien",    'text': "Vous pouvez voler\nune carte équipement\nà un autre joueur"}
];


const CARDS = {
  'Black' : [
    {'name': "Chauve-souris vampire", 'equip': false, 'desc': "Infligez 2 Blessures au joueur de votre choix, puis soignez une de vos Blessures."},
    {'name': "Chauve-souris vampire", 'equip': false, 'desc': "Infligez 2 Blessures au joueur de votre choix, puis soignez une de vos Blessures."},
    {'name': "Chauve-souris vampire", 'equip': false, 'desc': "Infligez 2 Blessures au joueur de votre choix, puis soignez une de vos Blessures."},
    {'name': "Succube tentatrice",    'equip': false, 'desc': "Volez une carte équipement au joueur de votre choix."},
    {'name': "Succube tentatrice",    'equip': false, 'desc': "Volez une carte équipement au joueur de votre choix."},
    {'name': "Araignée sanguinaire",  'equip': false, 'desc': "Vous infligez 2 Blessures au personnage de votre choix, puis vous subissez vous-même 2 Blessures."},
    {'name': "Poupée démoniaque",     'equip': false, 'desc': "Désignez un joueur et lancez le dé à 6 faces. 1 à 4 : infligez lui 3 Blessures. 5 ou 6 subissez 3 Blessures."},
    {'name': "Dynamite",              'equip': false, 'desc': "Lancez les 2 dés et infligez 3 Blessures à tous les joueurs (vous compris) se trouvant dans le secteur désigné par le total des 2 dés. Il ne se passe rien si ce total est 7."},
    {'name': "Rituel diabolique",     'equip': false, 'desc': "Si vous êtes un Shadow, et si vous décidez de révéler (ou avez déjà révélé) votre identité, soignez toutes vos Blessures."},
    {'name': "Peau de banane",        'equip': false, 'desc': "Donnez une de vos cartes équipements à un autre personnage. Si vous n'en possédez aucune, vous encaissez 1 Blessure."},
    {'name': "Tronçonneuse du mal",   'equip': true,  'desc': "Si votre attaque inflige des Blessures, la victime subit 1 Blessure en plus."},
    {'name': "Hachoir maudit",        'equip': true,  'desc': "Si votre attaque inflige des Blessures, la victime subit 1 Blessure en plus."},
    {'name': "Hache tueuse",          'equip': true,  'desc': "Si votre attaque inflige des Blessures, la victime subit 1 Blessure en plus."},
    {'name': "Revolver des ténèbres", 'equip': true,  'desc': "Vous pouvez attaquer un joueur présent sur l'un des 4 lieux hors de votre secteur, mais vous ne pouvez plus attaquer un joueur situé dans le même secteur que vous."},
    {'name': "Sabre hanté Masamuné",  'equip': true,  'desc': "Vous êtes obligé d'attaquer durant votre tour. Lancez uniquement le dé à 4 faces, le résultat indique les Blessures que vous infligez."},
    {'name': "Mitrailleuse funeste",  'equip': true,  'desc': "Votre attaque affecte tous les personnages qui sont à votre porté. Effectuez un seul jet de Blessures pour tous les joueurs concernés."}
  ],
  'White': [
    {'name': "Éclair purificateur", 'equip': false, 'desc': "Chaque personnage, à l'exception de vous même, subit 2 Blessures."},
    {'name': "Eau bénite",          'equip': false, 'desc': "Vous êtes soigné de 2 Blessures."},
    {'name': "Eau bénite",          'equip': false, 'desc': "Vous êtes soigné de 2 Blessures."},
    {'name': "Savoir ancestral",    'equip': false, 'desc': "Lorsque votre tour est terminé, jouez immédiatement un nouveau tour."},
    {'name': "Avènement suprème",   'equip': false, 'desc': "Si vous êtes un Hunter, vous pouvez révéler votre identité. Si vous le faites, ou si vous êtes déjà révélé, vous soignez toutes vos Blessures."},
    {'name': "Miroir divin",        'equip': false, 'desc': "Si vous êtes un Shadow, autre que Métamorphe, vous devez révéler votre identité."},
    {'name': "Premiers secours",    'equip': false, 'desc': "Placez le marqueur de Blessures du joueur de votre choix (y compris vous) sur le 7."},
    {'name': "Ange gardien",        'equip': false, 'desc': "Les attaques ne vous infligent aucune Blessure jusqu'à la fin de votre prochain tour."},
    {'name': "Barre de chocolat",   'equip': false, 'desc': "Si vous êtes Allie, Agnes, Emi, Ellen, Momie ou Métamorphe, et que vous choisissez de révéler (ou avez déjà révélé) votre identité, vous soignez toutes vos Blessures."},
    {'name': "Bénédiction",         'equip': false, 'desc': "Choisissez un joueur autre que vous même et lancez le dé à 6 faces. Ce joueur guérit d'autant de Blessures que le résultat du dé."},
    {'name': "Crucifix en argent",  'equip': true,  'desc': "Si vous attaquez et tuez un autre personnage, vous récupérez toutes ses cartes équipements."},
    {'name': "Toge sainte",         'equip': true,  'desc': "Vos attaques infligent 1 Blessure en moins, et les Blessures que vous subissez sont réduites de 1."},
    {'name': "Lance de Longinus",   'equip': true,  'desc': "Si vous êtes un Hunter, et que votre identité est révélée, chaque fois qu'une de vos attaque inflige des Blessures, vous infligez 2 Blessures supplémentaires."},
    {'name': "Amulette",            'equip': true,  'desc': "Vous ne subissez aucune Blessure causée par les cartes Ténèbres : Araignée sanguinaire, Dynamite ou Chauve-souris vampire."},
    {'name': "Broche de chance",    'equip': true,  'desc': "Un joueur dans la Forêt hantée ne peut pas utiliser le pouvoir du Lieu pour vous infliger des Blessures (mais il peut toujours vous guérir)."},
    {'name': "Boussole mystique",   'equip': true,  'desc': "Quand vous vous déplacez, vous pouvez lancer 2 fois les dés, et choisir quel résultat utiliser."},
  ],
  'Vision': [
    {'name': "Vision suprème",       'desc1': "",                                                              'desc2': "Monte moi secrètement ta carte Personnage !"},
    {'name': "Vision cupide",        'desc1': "Je pense que tu es Neutre ou Shadow",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure."},
    {'name': "Vision cupide",        'desc1': "Je pense que tu es Neutre ou Shadow",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure."},
    {'name': "Vision enivrante",     'desc1': "Je pense que tu es Neutre ou Hunter",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure"},
    {'name': "Vision enivrante",     'desc1': "Je pense que tu es Neutre ou Hunter",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure"},
    {'name': "Vision furtive",       'desc1': "Je pense que tu es Hunter ou Shadow",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure."},
    {'name': "Vision furtive",       'desc1': "Je pense que tu es Hunter ou Shadow",                           'desc2': "Si c'est le cas, tu dois : soit me donner une carte équipement, soit subir une Blessure."},
    {'name': "Vision mortifère",     'desc1': "Je pense que tu es Hunter",                                     'desc2': "Si c'est le cas, subis 1 Blessure !"},
    {'name': "Vision mortifère",     'desc1': "Je pense que tu es Hunter",                                     'desc2': "Si c'est le cas, subis 1 Blessure !"},
    {'name': "Vision destructrice",  'desc1': "Je pense que tu es un personnage de 12 Points de vie ou plus",  'desc2': "Si c'est le cas, subis 2 Blessures !"},
    {'name': "Vision clairvoyante",  'desc1': "Je pense que tu es un personnage de 11 Points de vie ou moins", 'desc2': "Si c'est le cas, subis 1 Blessures !"},
    {'name': "Vision divine",        'desc1': "Je pense que tu es Hunter",                                     'desc2': "Si c'est le cas, soigne 1 Blessure. (Toutefois, si tu n'avais aucune blessure, subis 1 Blessure !)"},
    {'name': "Vision réconfortante", 'desc1': "Je pense que tu es Neutre",                                     'desc2': "Si c'est le cas, soigne 1 Blessure. (Toutefois, si tu n'avais aucune blessure, subis 1 Blessure !)"},
    {'name': "Vision lugubre",       'desc1': "Je pense que tu es Shadow",                                     'desc2': "Si c'est le cas, soigne 1 Blessure. (Toutefois, si tu n'avais aucune blessure, subis 1 Blessure !)"},
    {'name': "Vision foudroyante",   'desc1': "Je pense que tu es Shadow",                                     'desc2': "Si c'est le cas, subis 1 Blessure !"},
    {'name': "Vision purificatrice", 'desc1': "Je pense que tu es Shadow",                                     'desc2': "Si c'est le cas, subis 2 Blessures !"}
  ]
};


if (typeof module !== 'undefined'){
  module.exports = {
    CHARACTERS: CHARACTERS,
    TEAMS: TEAMS,
    AREAS: AREAS,
    CARDS: CARDS,
  };
}
